#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

nginx_conf="/etc/nginx/sites-available/default"  # Update the path if needed
sed_pattern='\\t'"location ~ /redirect_me {\\n    \\t\\trewrite ^ https://sketchfab.com/bluepeno/models permanent;\\n\\t}"

sed -i "/server_name _;/a $sed_pattern" $nginx_conf

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
