#!/usr/bin/env bash
# Duplicating web-01 to web-02
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

nginx_conf="/etc/nginx/sites-available/default"  # Update the path if needed
sed_pattern='\\n\t'"error_page 404 /404.html;\\n \\tlocation = /404.html{\\n\\t\\tinternal;\\n\\t}\\n\\n"

sed -i "/server_name _;/a $sed_pattern" $nginx_conf

nginx_conf="/etc/nginx/sites-available/default"  # Update the path if needed
sed_pattern='\\t'"location ~ /redirect_me {\\n    \\t\\trewrite ^ https://sketchfab.com/bluepeno/models permanent;\\n\\t}"

sed -i "/server_name _;/a $sed_pattern" $nginx_conf

sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
