#!/bin/bash
echo "this is so cool damn"
git add .
echo -n "Enter commit message"
echo ==========================================================================
read message 
git commit -m '$message'
git push
