#!/bin/bash
clear
echo ===========================================================================
git add .
echo -n "Enter message"
echo ==========================================================================
read message 
git commit -m '$message'

git push
