#!/bin/bash
echo "this is so cool damn"
git add .
echo -n "Enter commit message"
echo 
echo ==========================================================================
read message 
git commit -m '$message'
echo ==========================================================================
echo "commiting done now its time for pushing"
echo =========================================================================
git push
