#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ];then
		echo "good luck"
	elif [ $counter -eq 8 ];then
		echo "bad luck"
	else
		echo "Best School"
	fi
	((counter++))
done
