#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=1
while [ $counter -eq 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "good luck"
	elif [ $counter -eq 8 ]
		echo "bad luck"
	else
		echo "Best School"
	fi
done
